//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruTexts_Customer_Management_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SuppID { get; set; }
        public int OrderID { get; set; }
        public int BookID { get; set; }
        public string SuppliersName { get; set; }
        public string CellNumber { get; set; }
        public string Address { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
